Added aikars recommended java GC flags.
agowa338/MinecraftSystemdUnit pull request #21
Opened 2020-06-06 21:00 UTC by Trikolon

See https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/ for a detailed explanation.

2020-06-06 22:07 UTC, agowa338 commented
It does not say which JVM this is for, is this for OpenJ9, HotSpot, something else (list available here: https://en.wikipedia.org/wiki/List_of_Java_virtual_machines)?

2020-06-07 10:23 UTC, Trikolon commented
We're using the default one that is packaged with `openjdk-11-jre` on Ubuntu. That's Hotspot and I'd assume it's what most people are using. This certainly can't be a one fits all solution, but I think it's a pretty sane default.

2020-06-07 11:11 UTC, agowa338 commented
ok, that should be fine.
Do you know what these two properties are used for?
```
-Dusing.aikars.flags=https://mcflags.emc.gs \
-Daikars.new.flags=true 
```

2020-06-07 11:21 UTC, Trikolon commented
I believe these are just used for indicating which version of aikars flags the server uses. He updates them from time to time. They also show up in timings reports of paper for easier performance troubleshooting.
They should have no effect on the actual JVM.

2020-06-07 13:21 UTC, agowa requested changes
I just did some lookup regarding the provided parameters and attached some feedback. Feel free to add to these, if you know more about them and there impact.

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:+PerfDisableSharedMem \
Will break things like jstat or other kinds of metric gathering.
Putting /tmp onto a tmpfs will also solve the io block issue.
```suggestion
```

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -Daikars.new.flags=true \
```suggestion
```

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -Dusing.aikars.flags=https://mcflags.emc.gs \
```suggestion
```

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:+AlwaysPreTouch \
Should we also recommend setting than? To only swap if less than 10% of memory are left?
```
sysctl -w vm.swappiness=10
```

and from your link, it says that it "mandates Transparent Huge Pages", what os has those enabled by default, do we need to add a manual for how to enable them? 
So from your link either `-XX:+UseLargePagesInMetaspace` or `-XX:+UseTransparentHugePages` should be set too?

It also looks like it isn't enabled by default on debian: https://wiki.debian.org/Hugepages

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:MaxTenuringThreshold=1 \
If (and only if) you know how to benchmark this value exactly, could you please add some data why 1 is better than any other value?
I've seen others use only values between 8 to 2, but however from reading about this parameter it looks like it should be set after benchmarking the application regarding it's exact runtime behavior with evacuation of eden space to the young collector.

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:+UnlockExperimentalVMOptions \
I'm not sure if using Experimental features for production environments is any good.
This will to people unintentionally breaking there minecraft when updating there system.
```suggestion
```

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:G1MixedGCLiveThresholdPercent=90 \
```suggestion
```
not stable, just experimental.
https://www.oracle.com/technical-resources/articles/java/g1gc.html

also it looks to be close to the default of 85 anyway. https://bugs.openjdk.java.net/browse/JDK-8059452

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:G1HeapWastePercent=5 \
```suggestion
```
This is the default value.
https://bugs.openjdk.java.net/browse/JDK-8059452

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:InitiatingHeapOccupancyPercent=15 \
The page you referenced says "10/4/2018: Removed AggressiveOpts and InitiatingHeapOccupancyPercent. Aggressive is removed in Java 11, and IHOP may hurt performance in Java 11. You should remove them for Java 8 too."
```suggestion
```

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:G1MaxNewSizePercent=40 \
```suggestion
```
not stable, just experimental

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:G1NewSizePercent=30 \
```suggestion
```
not stable just experimental.

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:+DisableExplicitGC \
Disabling explicit gc entirely could lead to some already badly behaving code to bail out entirely. It also destroys reasonable usages of explicit gc invocations, how about this (it still prevents stop the world issues, but with less risks):
```suggestion
          -XX:+ExplicitGCInvokesConcurrent \
          -XX:+CMSClassUnloadingEnabled \
```

2020-06-07 13:21 UTC, agowa commented on minecraft@.service
> +          -XX:MaxGCPauseMillis=200 \
```suggestion
```
This is the default value. https://www.oracle.com/technical-resources/articles/java/g1gc.html and https://github.com/openjdk/jdk/blob/9a69bb807beb6693c68a7b11bee435c0bab7ceac/src/hotspot/share/gc/g1/g1Arguments.cpp#L161

2020-06-09 10:13 UTC, Trikolon commented
Thanks for looking into this! Haven't had time to work in a revision yet.
I'm not an expert on JVMs. Maybe @aikar would be interested in joining this discussion.

2021-12-12 12:49 UTC, agowa338 commented
No activity for >1 year. Closing this now.

2021-12-12 12:49 UTC, closed without merging